language: node_js
node_js: '9'
services:
- postgresql
before_script:
- psql -c 'create database happy_hour_hero;' -U postgres
- psql -c 'create database happy_hour_hero_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: G7/krfum8y36T8CiO0iHPPb9x0Mq4fK961BwTXsxzJDyJbCDlt7bnRmKRJn8KlcnDTRKp8VkSdRX/QoL8fJRajNl29ue9GdA4XxYqNfjLXWFrAU/z45pGBS6OKRK50HGkKojHOtBShLO+JtdpZCJiACoGtJ1EkB7rldxiKf0FW9ZHHJmybk2J1VlMKZmSCYLTetrTe3PWOI2XUbZdbV133eSUl3vbtPK/WuS8EW+Le7bhTH7fgdNmYu7DUSSsSbjQ9IdEPl+frVMARrKwDcAx3Z+EfV/g3ECj/5FFNaNL3zBZ4f3bChuIQYypSbcy2dxeeIjPkSaAR1Ze67j0VCWIua7Fco6yjRTn/VKXSbKJgiGGXda3hG69SNpNvVM0XOTfCoJ28lvnhhbMhQVkx4365R7c+doACXM8PDlfxyFlDhua0zip7Sw5bWXKZo7YvCvhntE2hQzKbjoXFjQpAGMGFtH1I/ZJV1WD9rlK1R5gHWpJCSWmDSW4oWztziljXRS4/6jGLrQE36S6Jh9DGIgOQAcB7oc02KGlyeM2vfo5mS8Hgg6oMDgcMnFMCQ2UPdZoq4AMXoYC/uBbMzJAHmefMeuqQTWJ7ZWI0J84wYP8xuWVWkNo06ApMZCz06m9ELS/ZJDqXSG1lEdkmTNG8tgyQ9xY9LyzBL8JR+6Dmb0mFQ=
  app: happy_hour_hero
  skip_cleanup: true
env:
  global:
  - secure: M0PAwCZvctwkHS/u1zn286J4r3e4lyvpnlG3QzRC5Fxw9cToHcmoig6KuUwG+KawFD53wXC6LtRut1abCHNt8CmwyZGfwUN01zCZLQxaqXgmTICmc6DLTztjRNdcfAktjEHKLshDpRq54EpQpiWI2wA/ZWkBwNwMdSKqZ7cci7J5AvSzwUKa99N6+gp4GtwPZ1GB+d9u73prdI2GMEpyQ27JlWE/XFeu+MxXyEk78JfMOgQT2c4rBlYZREROfzAc7b9G8kZ+YKZJnhmApH4VIdKWf69kp5MEX9qWyztxZPkdy6k2LQD40ojfzPdPeivdCQCnYDw7y5LtOXStsau1cZcL04NqyB6Px3WFIFbVVazU7Hu31ioV7g4rQGYU1jIiaZq7ufN0nisMGk2/ndCHMO083N5hZ2/oQLVoUKHlF2433X8trzmBegvzruoTA+tzDSmAUcJc/Sf8x+fz02mtj7+X7peLeo6yY0Okd9KWlrz5E+BbcLdBK0Sh0nEMwp8eWQv+urVLN5rX8ndoxgY1EuKr5GBMcnGn+kuoBAdqzywSdkTAL7uq095Uy8iPk+/T3eimrEc32tKU9Y4lAnKRLR67EG7VPw2wtjzfWViaSuz5dh/WqZr7fGWLEtSmhZjMGmtH3djXly4Qb4JqweK4BhqmwH4Upu3z+BETv+1xcKs=
