const happy_hour_data = require('../data/z_happy_hour_data');

exports.seed = function (knex, Promise) {
  let restaurant_id;
  let food_specials_id;
  let drink_specials_id;

  return knex('happy_hours').del()
    .then(() => {
      return Promise.all([
        knex('restaurants').select()
          .then(restaurant => (restaurant_id = restaurant))
      ]);
    })
    .then(() => {
      return Promise.all([
        knex('drink_specials').select()
          .then(drink_specials => (drink_specials_id = drink_specials))
      ]);
    })
    .then(() => {
      return Promise.all([
        knex('food_specials').select()
          .then(food_specials => (food_specials_id = food_specials))
      ]);
    })
    .then(() => {
      return Promise.all([
        knex('happy_hours').insert([
          // Brothers
          { day: 'Monday', start_time: '1600', end_time: '2000', combined_times: '4:00PM-8:00PM', drink_specials_id: drink_specials_id[0].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Monday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[3].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Monday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[4].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Tuesday', start_time: '1600', end_time: '2000', combined_times: '4:00PM-8:00PM', drink_specials_id: drink_specials_id[0].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Tuesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[5].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Tuesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[2].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Tuesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[6].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Wednesday', start_time: '1600', end_time: '2000', combined_times: '4:00PM-8:00PM', drink_specials_id: drink_specials_id[0].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Wednesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[7].id, food_specials_id: food_specials_id[0].id, restaurant_id: restaurant_id[0].id },
          { day: 'Wednesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[8].id, food_specials_id: food_specials_id[0].id, restaurant_id: restaurant_id[0].id },
          { day: 'Wednesday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[9].id, food_specials_id: food_specials_id[0].id, restaurant_id: restaurant_id[0].id },
          { day: 'Thursday', start_time: '1600', end_time: '2000', combined_times: '4:00PM-8:00PM', drink_specials_id: drink_specials_id[0].id, food_specials_id: null, restaurant_id: restaurant_id[0].id, },
          { day: 'Thursday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[10].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[0].id },
          { day: 'Thursday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[2].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[0].id },
          { day: 'Thursday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[9].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[0].id },
          { day: 'Thursday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[11].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[0].id },
          { day: 'Friday', start_time: '1600', end_time: '2000', combined_times: '4:00PM-8:00PM', drink_specials_id: drink_specials_id[0].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Friday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[12].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Friday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[13].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Friday', start_time: '2000', end_time: '200'.padStart(4, '0'), combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[14].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Saturday', start_time: '1100', end_time: '200'.padStart(4, '0'), combined_times: '11:00AM-2:00AM', drink_specials_id: drink_specials_id[1].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          { day: 'Sunday', start_time: '1100', end_time: '200'.padStart(4, '0'), combined_times: '11:00PM-2:00AM', drink_specials_id: drink_specials_id[2].id, food_specials_id: null, restaurant_id: restaurant_id[0].id },
          // Hapa
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Monday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Tuesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Wednesday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Thursday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[4].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Friday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[4].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Saturday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[4].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '1430', end_time: '1800', combined_times: '2:30PM-6:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[15].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[16].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[17].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[18].id, food_specials_id: food_specials_id[2].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[19].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[20].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[21].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          { day: 'Sunday', start_time: '2200', end_time: '2300', combined_times: '10:00PM-11:00PM', drink_specials_id: drink_specials_id[22].id, food_specials_id: food_specials_id[3].id, restaurant_id: restaurant_id[1].id },
          // Falling Rock
          { day: 'Monday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[2].id, food_specials_id: null, restaurant_id: restaurant_id[2].id },
          { day: 'Tuesday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[5].id, food_specials_id: food_specials_id[0].id, restaurant_id: restaurant_id[2].id },
          { day: 'Wednesday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[12].id, food_specials_id: food_specials_id[0].id, restaurant_id: restaurant_id[2].id },
          { day: 'Thursday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[9].id, food_specials_id: null, restaurant_id: restaurant_id[2].id },
          { day: 'Friday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[1].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[2].id },
          { day: 'Saturday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[7].id, food_specials_id: null, restaurant_id: restaurant_id[2].id },
          { day: 'Sunday', start_time: '1600', end_time: '100'.padStart(4, '0'), combined_times: '4:00PM-1:00AM', drink_specials_id: drink_specials_id[4].id, food_specials_id: food_specials_id[1].id, restaurant_id: restaurant_id[2].id },
          // Crow Bar
          { day: 'Monday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Monday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Thursday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Thursday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Friday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Friday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Saturday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Saturday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Sunday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[23].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          { day: 'Sunday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[24].id, food_specials_id: null, restaurant_id: restaurant_id[3].id },
          // Tennyson Tap
          { day: 'Monday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Monday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Monday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Thursday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Thursday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Thursday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Friday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Friday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Friday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Saturday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Saturday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Saturday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Sunday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[25].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Sunday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[26].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          { day: 'Sunday', start_time: '1400', end_time: '1900', combined_times: '2:00PM-7:00PM', drink_specials_id: drink_specials_id[27].id, food_specials_id: null, restaurant_id: restaurant_id[4].id },
          // Sloans Bar & Grill
          { day: 'Monday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[28].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Monday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[29].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Monday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[30].id, food_specials_id: food_specials_id[6].id, restaurant_id: restaurant_id[5].id },
          { day: 'Monday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[31].id, food_specials_id: food_specials_id[7].id, restaurant_id: restaurant_id[5].id },
          { day: 'Monday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[32].id, food_specials_id: food_specials_id[8].id, restaurant_id: restaurant_id[5].id },
          { day: 'Tuesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[28].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Tuesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[29].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Tuesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[30].id, food_specials_id: food_specials_id[6].id, restaurant_id: restaurant_id[5].id },
          { day: 'Tuesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[31].id, food_specials_id: food_specials_id[7].id, restaurant_id: restaurant_id[5].id },
          { day: 'Tuesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[32].id, food_specials_id: food_specials_id[8].id, restaurant_id: restaurant_id[5].id },
          { day: 'Wednesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[28].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Wednesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[29].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Wednesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[30].id, food_specials_id: food_specials_id[6].id, restaurant_id: restaurant_id[5].id },
          { day: 'Wednesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[31].id, food_specials_id: food_specials_id[7].id, restaurant_id: restaurant_id[5].id },
          { day: 'Wednesday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[32].id, food_specials_id: food_specials_id[8].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[28].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[29].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[30].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[31].id, food_specials_id: food_specials_id[6].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[32].id, food_specials_id: food_specials_id[7].id, restaurant_id: restaurant_id[5].id },
          { day: 'Thursday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[33].id, food_specials_id: food_specials_id[8].id, restaurant_id: restaurant_id[5].id },
          { day: 'Friday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[28].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Friday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[29].id, food_specials_id: food_specials_id[5].id, restaurant_id: restaurant_id[5].id },
          { day: 'Friday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[30].id, food_specials_id: food_specials_id[6].id, restaurant_id: restaurant_id[5].id },
          { day: 'Friday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[31].id, food_specials_id: food_specials_id[7].id, restaurant_id: restaurant_id[5].id },
          { day: 'Friday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[32].id, food_specials_id: food_specials_id[8].id, restaurant_id: restaurant_id[5].id },
          { day: 'Saturday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[34].id, food_specials_id: null, restaurant_id: restaurant_id[5].id },
          { day: 'Saturday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[35].id, food_specials_id: null, restaurant_id: restaurant_id[5].id },
          { day: 'Sunday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[34].id, food_specials_id: null, restaurant_id: restaurant_id[5].id },
          { day: 'Sunday', start_time: '1400', end_time: '1800', combined_times: '2:00PM-6:00PM', drink_specials_id: drink_specials_id[35].id, food_specials_id: null, restaurant_id: restaurant_id[5].id },
          // Clancy's Irish Pub
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Saturday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Saturday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Saturday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Saturday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Sunday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[36].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Sunday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[37].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Sunday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[38].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          { day: 'Sunday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: food_specials_id[9].id, restaurant_id: restaurant_id[6].id },
          // Joyride Brewing Company
          { day: 'Monday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Thursday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Friday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Saturday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          { day: 'Sunday', start_time: '1600', end_time: '1900', combined_times: '4:00PM-7:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[7].id },
          // Terminal Bar
          { day: 'Monday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[40].id, food_specials_id: null, restaurant_id: restaurant_id[8].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[40].id, food_specials_id: null, restaurant_id: restaurant_id[8].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[40].id, food_specials_id: null, restaurant_id: restaurant_id[8].id },
          { day: 'Thursday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[40].id, food_specials_id: null, restaurant_id: restaurant_id[8].id },
          { day: 'Friday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[40].id, food_specials_id: null, restaurant_id: restaurant_id[8].id },
          // Star Bar - No Data found
          // Wynkoop Brewing Company
          { day: 'Monday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: drink_specials_id[41].id, food_specials_id: null, restaurant_id: restaurant_id[10].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: drink_specials_id[41].id, food_specials_id: null, restaurant_id: restaurant_id[10].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: drink_specials_id[41].id, food_specials_id: null, restaurant_id: restaurant_id[10].id },
          { day: 'Thursday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: drink_specials_id[41].id, food_specials_id: null, restaurant_id: restaurant_id[10].id },
          { day: 'Friday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: drink_specials_id[41].id, food_specials_id: null, restaurant_id: restaurant_id[10].id },
          // Moo Bar - No Data found
          // 1 Up
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[42].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[43].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[44].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Monday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[45].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[42].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[43].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[44].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[45].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[42].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[43].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[44].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[45].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[42].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[43].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[44].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Thursday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[45].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[42].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[43].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[44].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          { day: 'Friday', start_time: '1500', end_time: '1900', combined_times: '3:00PM-7:00PM', drink_specials_id: drink_specials_id[45].id, food_specials_id: null, restaurant_id: restaurant_id[12].id },
          // Machete Tequila + Tacos
          { day: 'Monday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Tuesday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Wednesday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Thursday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Friday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Saturday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          { day: 'Sunday', start_time: '1500', end_time: '1800', combined_times: '3:00PM-6:00PM', drink_specials_id: null, food_specials_id: null, restaurant_id: restaurant_id[13].id },
          // The Pour House Pub
          { day: 'Monday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[46].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Monday', start_time: '2000', end_time: '2600', combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[51].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Monday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Tuesday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[46].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Tuesday', start_time: '2000', end_time: '2600', combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[51].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Tuesday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Wednesday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[46].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Wednesday', start_time: '2000', end_time: '2600', combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[52].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Wednesday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Thursday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[46].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Thursday', start_time: '2000', end_time: '2600', combined_times: '8:00PM-2:00AM', drink_specials_id: drink_specials_id[53].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Thursday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Friday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[46].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Friday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Saturday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[48].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Saturday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[49].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Saturday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[50].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Saturday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[54].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Sunday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[48].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Sunday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[49].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Sunday', start_time: '1400', end_time: '2000', combined_times: '2:00PM-8:00PM', drink_specials_id: drink_specials_id[50].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          { day: 'Sunday', start_time: '1400', end_time: '2600', combined_times: '2:00PM-2:00AM', drink_specials_id: drink_specials_id[55].id, food_specials_id: null, restaurant_id: restaurant_id[14].id },
          // Spangalang
          { day: 'Wednesday', start_time: '1800', end_time: '2200', combined_times: '6:00PM-10:00PM', drink_specials_id: null, food_specials_id: food_specials_id[10].id, restaurant_id: restaurant_id[15].id },
          // The Denver Bicycle Cafe
          { day: 'Monday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Monday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Tuesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Tuesday', start_time: '1600', end_time: '2400', combined_times: '4:00PM-12:00AM', drink_specials_id: drink_specials_id[56].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Tuesday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Wednesday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Wednesday', start_time: '1600', end_time: '2400', combined_times: '4:00PM-12:00AM', drink_specials_id: drink_specials_id[57].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Wednesday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Thursday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Thursday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Friday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Friday', start_time: '1600', end_time: '2400', combined_times: '4:00PM-12:00AM', drink_specials_id: drink_specials_id[58].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Friday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Saturday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Saturday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Sunday', start_time: '1600', end_time: '1800', combined_times: '4:00PM-6:00PM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          { day: 'Sunday', start_time: '2200', end_time: '2400', combined_times: '10:00PM-12:00AM', drink_specials_id: drink_specials_id[39].id, food_specials_id: null, restaurant_id: restaurant_id[16].id },
          // Illegal Pete's
          { day: 'Monday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Tuesday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Wednesday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Thursday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Friday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Saturday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id },
          { day: 'Sunday', start_time: '1500', end_time: '2000', combined_times: '3:00PM-8:00PM', drink_specials_id: drink_specials_id[59].id, food_specials_id: null, restaurant_id: restaurant_id[17].id }
        ])
      ]);
    })
    .then(() => console.log('Seeding complete!'))
    .catch(error => console.log(`Error seeding data: ${error}`));
}